### ISSUE TITLE
TypeError when requiring react-redux

### ISSUE THREAD

**Issue by davidnorth** [gaearon/react-redux#49]
When requiring react-redux either via Browserify or in the Node REPL, I get the following:

    TypeError: Super expression must either be null or a function, not undefined
        at _inherits (/Users/davidnorth/Sites/x/node_modules/react-redux/lib/components/createProvider.js:13:113)
        at /Users/davidnorth/Sites/xxx/node_modules/react-redux/lib/components/createProvider.js:26:5
        at Object.createProvider [as default] (/Users/davidnorth/Sites/x/node_modules/react-redux/lib/components/createProvider.js:70:5)

My version is 0.8.0

**Comment by gaearon** [comment]
Which version of React are you using? What do you use to compile JSX?

**Comment by davidnorth** [comment]
React 0.12.2 an babelyify 6.0.2

**Comment by gaearon** [comment]
React Redux requires React 0.13.
https://github.com/gaearon/react-redux/blob/master/package.json#L53
